version: '3'
services:
  app:
    build: ./
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    ports:
      - 8000:8000
    command: php -S 0.0.0.0:8000 -t public/
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./.data:/var/lib/mysql
